name: Push the Docker image to AWS ECR Repo
on:
  push:
    branches:
      - master
jobs:
  build_gmx:
    # We do not need to check out the repository to use the reusable workflow
    uses: ./.github/workflows/reusable_docker_build.yml
    with:
      image_name: "unhosted_backend_gmx"
      dockerfile: "Dockerfile"
      service_name: "gmx"
    secrets:
      # Can also implicitly pass the secrets with: secrets: inherit
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PAT: ${{ secrets.PAT }}